package com.produck.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SplitBookJoinerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSplitBookJoinerAllPropertiesEquals(SplitBookJoiner expected, SplitBookJoiner actual) {
        assertSplitBookJoinerAutoGeneratedPropertiesEquals(expected, actual);
        assertSplitBookJoinerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSplitBookJoinerAllUpdatablePropertiesEquals(SplitBookJoiner expected, SplitBookJoiner actual) {
        assertSplitBookJoinerUpdatableFieldsEquals(expected, actual);
        assertSplitBookJoinerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSplitBookJoinerAutoGeneratedPropertiesEquals(SplitBookJoiner expected, SplitBookJoiner actual) {
        assertThat(expected)
            .as("Verify SplitBookJoiner auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSplitBookJoinerUpdatableFieldsEquals(SplitBookJoiner expected, SplitBookJoiner actual) {
        assertThat(expected)
            .as("Verify SplitBookJoiner relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSplitBookJoinerUpdatableRelationshipsEquals(SplitBookJoiner expected, SplitBookJoiner actual) {
        assertThat(expected)
            .as("Verify SplitBookJoiner relationships")
            .satisfies(e -> assertThat(e.getSplitBook()).as("check splitBook").isEqualTo(actual.getSplitBook()));
    }
}
